# -*- coding: utf-8 -*-
"""PDF 2 ICS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cukJWYEEJ3yPdAmzARueGBWSWNN58R2c
"""

import nltk

nltk.download("wordnet")
