name: deploy

on:
  schedule:
    - cron: '30 5 1 * *'  # the first day of every month at 5:30 UTC
    - cron: '30 5 2 * *'  # the second day of every month at 5:30 UTC
    - cron: '30 5 3 * *'  # the third day of every month at 5:30 UTC
    - cron: '30 5 4 * *'  # the fourth day of every month at 5:30 UTC
    - cron: '30 5 5 * *'  # the fifth day of every month at 5:30 UTC

jobs:
  create_ics:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.11
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python setup.py

    - name: Build ics files
      run: |
        python pdf_2_ics.py
      
    - name: Publish files
      uses: actions/upload-artifact@v4
      with:
        name: calendars
        path: ./*.ics
