name: deploy

on:
  push:
  schedule:
    - cron: '30 5 1 * *'  # the first day of every month at 5:30 UTC
    - cron: '30 5 2 * *'  # the second day of every month at 5:30 UTC
    - cron: '30 5 3 * *'  # the third day of every month at 5:30 UTC
    - cron: '30 5 4 * *'  # the fourth day of every month at 5:30 UTC

jobs:
  create_ics:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.11
        cache: 'pip' # caching pip dependencies
      run: pip install -r requirements.txt

    - name: Install dependencies
      run: |
        python setup.py

    - name: Build ics files
      run: |
        python pdf_2_ics.py
      
    - name: Publish files
      uses: actions/upload-artifact@v4
      with:
        name: calendars
        path: ./*.ics

    - name: Publish files 2
      uses: actions/upload-artifact@v4
      with:
        name: old_links
        path: ./old_links.json

    - name: Decrypt large secret
      run: |
        ./decrypt_secret.sh
        python test_decrypt.py
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

    - name: Post new menus to calendars
      run: |
        python gcal.py
  